// Code generated by `mygo generate`. DO NOT EDIT.

import { call } from "mygo-runtime";

// ---- Types ----

export interface HealthStatus {
  status: string;
  runtime: string;
  startedAt: string;
}

// ---- Services ----

/** HealthService is the first typed bridge exposed to the MyGo shell. */
export const HealthService = {
  health(): Promise<HealthStatus> {
    return call("HealthService.Health");
  },
} as const;
